### PR TITLE
Added new editor config file for consistent code formatting

### LINKED ISSUE #211: Add a EditorConfig file?
I suggest adding a EditorConfig file to the project to enforce consistent coding styles for everyone that works in the codebase.
I also suggest that all existing code gets formatted once to create a new base plate for any new PRs.

### PR DESCRIPTION
**Pull request by Eneuman**
This PR adds a .editorConfig file so that everyone contributing to this project uses the same formating rules.
The added .editorConfig file uses the standard VS 2022 settings.

This file together with VS 2022 Code Cleanup on save feature (https://devblogs.microsoft.com/visualstudio/bringing-code-cleanup-on-save-to-visual-studio-2022-17-1-preview-2/) ensures clean code and removes the problem with different formatting  in future PRs.

Closes #211

### CODE REVIEW

**Comment by Eneuman** [comment]
@hsubramanianaks yeah, right now it just adds the editor config. I did a test formatting of everything and that PR got huge. GitHub's code review tool didn't work very well when comparing those changes so I think it's best to do the formatting in a separate PR without any code change at all. Also with a lot of PRs going on there is a high risk of merge conflicts so if it's okey I'll wait until there are less PR then post that one?

**Comment by Eneuman** [comment]
No worries :) Thanks for the info.

**Comment by hsubramanianaks** [comment]
> @hsubramanianaks I also choose to add it as a solution file to the all.csproj project. Let me know if you don't want it to show up in the solution and I'll remove it.

I guess applying to all.sln should apply this .editorconfig to all projects right including tests ? I believe when you do the other PR it would be helpful to apply your style changes to all projects.

**Comment by Eneuman** [comment]
@hsubramanianaks VS will use the file for any project located in any sub directory :) 

I only added it to all.csproj so it could easier be edited and for contributors to see it so they know why there local formatting rules are not applied.

**Comment by hsubramanianaks** [comment]
> 

Thanks for the confirmation. I think there is no need of testing for this PR since it is just editor config, builds passed as well. I will merge your change. Thanks for the PR.

**Pull request merged**
