### PR TITLE
Added jaeger-agent as known sidecar

### PR DESCRIPTION
**Pull request by BartNetJS**
See also https://github.com/Azure/Bridge-To-Kubernetes/issues/292

This PR allows Jaeger side car support by bridge.

### CODE REVIEW

**Review by hsubramanianaks — APPROVED** [review]
looks good to me. I would suggest testing this fully before merging and releasing it. Because I feel there might some other places in the code might need tweaks.

**Comment by hsubramanianaks** [comment]
> Hi @hsubramanianaks, Do you expect me to do something to get it approved by your colleagues?

@BartNetJS I can generate a VSIX with your fix and you can test it with Jeager sidecars to see if it works ? So that we can confirm it works fully. Please let me know. After this we can other code owners to review and give their comments/approval.

**Comment by hsubramanianaks** [comment]
> > Hi @hsubramanianaks, Do you expect me to do something to get it approved by your colleagues?
> 
> @BartNetJS I can generate a VSIX with your fix and you can test it with Jeager sidecars to see if it works ? So that we can confirm it works fully. Please let me know. After this we can ask other code owners to review and give their comments/approval.

@BartNetJS here is the VSIX - https://github.com/hsubramanianaks/vscode-bridge-to-kubernetes/releases/tag/jeager-support, please set BRIDGE_ENVIRONMENT='dev' and then install VSIX and run your apps with Jeager to see if it works. Thank you.

**Comment by BartNetJS** [comment]
> > > Hi @hsubramanianaks, Do you expect me to do something to get it approved by your colleagues?
> > 
> > 
> > @BartNetJS I can generate a VSIX with your fix and you can test it with Jeager sidecars to see if it works ? So that we can confirm it works fully. Please let me know. After this we can ask other code owners to review and give their comments/approval.
> 
> @BartNetJS here is the VSIX - https://github.com/hsubramanianaks/vscode-bridge-to-kubernetes/releases/tag/jeager-support, please set BRIDGE_ENVIRONMENT='dev' and then install VSIX and run your apps with Jeager to see if it works. Thank you.

The vsix gives an error:

17/07/2023 10:41:23 - Microsoft VSIX Installer
17/07/2023 10:41:23 - -------------------------------------------
17/07/2023 10:41:23 - vsixinstaller.exe version:
17/07/2023 10:41:23 - 17.6.2166+g22f8bbf459
17/07/2023 10:41:23 - -------------------------------------------
17/07/2023 10:41:23 - Command line parameters:
17/07/2023 10:41:23 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\BartVanderAuweraert\Downloads\mindaro-2.0.120230714-pull294.vsix
17/07/2023 10:41:23 - -------------------------------------------
17/07/2023 10:41:23 - Microsoft VSIX Installer
17/07/2023 10:41:23 - -------------------------------------------
17/07/2023 10:41:23 - Initializing Install...
17/07/2023 10:41:23 - Searching for applicable products...
17/07/2023 10:41:24 - System.Reflection.TargetInvocationException: Het doel van een aanroep heeft een uitzondering veroorzaakt. ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: De indeling van de invoertekenreeks is onjuist.
   bij System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   bij System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   bij System.Version.TryParseVersion(String version, VersionResult& result)
   bij System.Version.Parse(String input)
   bij System.Version..ctor(String version)
   bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__76_1(String s)
   bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- Einde van intern uitzonderingsstackpad ---
   bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   bij Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   bij Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   --- Einde van intern uitzonderingsstackpad ---
   bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bij System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bij System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bij System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bij System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bij VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
   bij VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bij VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bij VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bij VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bij VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bij VSIXInstaller.App.Initialize()
   bij System.Threading.Tasks.Task`1.InnerInvoke()
   bij System.Threading.Tasks.Task.Execute()
   
   
If posisble can you give a vscode extension?

**Comment by hsubramanianaks** [comment]
> > > > Hi @hsubramanianaks, Do you expect me to do something to get it approved by your colleagues?
> 
> > > 
> 
> > > 
> 
> > > @BartNetJS I can generate a VSIX with your fix and you can test it with Jeager sidecars to see if it works ? So that we can confirm it works fully. Please let me know. After this we can ask other code owners to review and give their comments/approval.
> 
> > 
> 
> > @BartNetJS here is the VSIX - https://github.com/hsubramanianaks/vscode-bridge-to-kubernetes/releases/tag/jeager-support, please set BRIDGE_ENVIRONMENT='dev' and then install VSIX and run your apps with Jeager to see if it works. Thank you.
> 
> 
> 
> The vsix gives an error:
> 
> 
> 
> 17/07/2023 10:41:23 - Microsoft VSIX Installer
> 
> 17/07/2023 10:41:23 - -------------------------------------------
> 
> 17/07/2023 10:41:23 - vsixinstaller.exe version:
> 
> 17/07/2023 10:41:23 - 17.6.2166+g22f8bbf459
> 
> 17/07/2023 10:41:23 - -------------------------------------------
> 
> 17/07/2023 10:41:23 - Command line parameters:
> 
> 17/07/2023 10:41:23 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\BartVanderAuweraert\Downloads\mindaro-2.0.120230714-pull294.vsix
> 
> 17/07/2023 10:41:23 - -------------------------------------------
> 
> 17/07/2023 10:41:23 - Microsoft VSIX Installer
> 
> 17/07/2023 10:41:23 - -------------------------------------------
> 
> 17/07/2023 10:41:23 - Initializing Install...
> 
> 17/07/2023 10:41:23 - Searching for applicable products...
> 
> 17/07/2023 10:41:24 - System.Reflection.TargetInvocationException: Het doel van een aanroep heeft een uitzondering veroorzaakt. ---> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: De indeling van de invoertekenreeks is onjuist.
> 
>    bij System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
> 
>    bij System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
> 
>    bij System.Version.TryParseVersion(String version, VersionResult& result)
> 
>    bij System.Version.Parse(String input)
> 
>    bij System.Version..ctor(String version)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__76_1(String s)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
> 
>    --- Einde van intern uitzonderingsstackpad ---
> 
>    bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
> 
>    bij Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
> 
>    --- Einde van intern uitzonderingsstackpad ---
> 
>    bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> 
>    bij System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> 
>    bij System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
> 
>    bij System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
> 
>    bij System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
> 
>    bij VSIXInstaller.ExtensionEngineFactoryForSku.GetTypeFromEngine[TInterface](SupportedVSSKU sku, String typeName, Object[] constructorArguments)
> 
>    bij VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
> 
>    bij VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
> 
>    bij VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
> 
>    bij VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
> 
>    bij VSIXInstaller.App.Initialize(Boolean isRepairSupported)
> 
>    bij VSIXInstaller.App.Initialize()
> 
>    bij System.Threading.Tasks.Task`1.InnerInvoke()
> 
>    bij System.Threading.Tasks.Task.Execute()
> 
>    
> 
>    
> 
> If posisble can you give a vscode extension?

This vsix is for vscode extension not Visual studio. Sorry I should have mentioned this. Please try and let me know. @BartNetJS

**Comment by BartNetJS** [comment]
@hsubramanianaks I got his popups when i try to debug(local tunnel)

image

**Comment by BartNetJS** [comment]
@hsubramanianaks forgot to set it, sorry for that
It is working!

**Comment by hsubramanianaks** [comment]
> @hsubramanianaks forgot to set it, sorry for that It is working!

@cxznmhdcxz can you do internal round of testing and confirm on the results please?

**Comment by cxznmhdcxz** [comment]
Passed on all 3 platforms

**Pull request merged**
