### PR TITLE
Json patch issue fix for stateful sets

### PR DESCRIPTION
**Pull request by hsubramanianaks**
This PR will fix two issues

Issue#1 [Issue](https://github.com/Azure/Bridge-To-Kubernetes/issues/235)

- When debugging stateful set apps using bridge to kubernetes , patching the stateful apps were failing with error ```json: cannot unmarshal object into Go value of type``` , fixing it by serializing the json patch document (object to json string) might fix this issue. 
Thanks @Eneuman for the hint, user confirmed it is working. :)

Issue#2 
fix the issue of using ```KubernetesLocalProcessConfig.yaml``` to mount volumes which would fail due to missing tar dependency in docker file. Error log below for reference. 

```System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'tar' with working directory '/src/devhostagent'. No such file or directory
         at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
         at Microsoft.BridgeToKubernetes.DevHostAgent.Controllers.DownloadController.RunTar(String commandLine) in /src/devhostagent/Controllers/DownloadController.cs:line 87
         at Microsoft.BridgeToKubernetes.DevHostAgent.Controllers.DownloadController.RunTarDirectory(String targetFile, String sourceDirectory) in /src/devhostagent/Controllers/DownloadController.cs:line 62
         at Microsoft.BridgeToKubernetes.DevHostAgent.Controllers.DownloadController.DownloadFiles(String path) in /src/devhostagent/Controllers/DownloadController.cs:line 49```

### CODE REVIEW

**Review by bfoley13 — APPROVED** [review]
Changes look good

**Review by Tatsinnit — APPROVED** [review]
🎉🪄☕️

**Review by Tatsinnit — APPROVED** [review]

**Review by hsubramanianaks — COMMENTED** [review]
Testing team confirmed E2E working for windows, linux. Waiting for mac approval.

**Comment by hsubramanianaks** [comment]
> Testing team confirmed E2E working for windows, linux. Waiting for mac approval.

Mac platform tests also passed.

**Pull request merged**
