### PR TITLE
Added SupportedOSPlatformGuard and new improved operating system identification

### LINKED ISSUE #212: Replace Platform operating system identification with .Net 6 native code
In Platform.cs we have the following code:
```
        private readonly Lazy<bool> _isWindows = new Lazy<bool>(() => RuntimeInformation.IsOSPlatform(OSPlatform.Windows));
        private readonly Lazy<bool> _isOSX = new Lazy<bool>(() => RuntimeInformation.IsOSPlatform(OSPlatform.OSX));
        private readonly Lazy<bool> _isLinux = new Lazy<bool>(() => RuntimeInformation.IsOSPlatform(OSPlatform.Linux));

        public bool IsWindows => _isWindows.Value;
        public bool IsOSX => _isOSX.Value;
        public bool IsLinux => _isLinux.Value;
```

.Net 5 introduced new methods for identifying the running operating system:
`OperatingSystem.IsWindows()` `OperatingSystem.IsLinux()`  `OperatingSystem.IsMacOS()`

Theese new methods are implemented using preprocessor directives to fix the return value to a constant true/false at compilation time for each target OS the OperatingSystem class is compiled for. There is no runtime probing or calls to make so they are fast.

If we replace the custom code with the new .Net 5+ methods and add `[SupportedOSPlatformGuard]` to the "Is" properties, most of the `CA1416: Validate platform compatibility` warnings will go away and performance will be improved.

### PR DESCRIPTION
**Pull request by Eneuman**
This PR uses the new improved methods `OperatingSystem.IsWindows()` `OperatingSystem.IsLinux()` `OperatingSystem.IsMacOS()` to identify the running operating system.

Theese new methods are implemented using preprocessor directives to fix the return value to a constant true/false at compilation time for each target OS the OperatingSystem class is compiled for. There is no runtime probing or calls to make.

The PR also adds `SupportedOSPlatformGuard` attributs to the custom guards. This removed 68 warnings from the build log.

Closes #212

### CODE REVIEW

**Review by elenavillamil — COMMENTED** [review]
Looks good. Let me send it to testing team.

**Review by hsubramanianaks — APPROVED** [review]
LGTM

**Comment by hsubramanianaks** [comment]
Closing PR to kick in chatGPT review.

**Comment by hsubramanianaks** [comment]
@Eneuman Testing team confirmed it works in windows and Linux. Waiting for confirmation on Mac and then will merge this. Thank you.

**Pull request merged**
