### PR TITLE
Update sample todo app dependencies

### PR DESCRIPTION
**Pull request by elenavillamil**
Update dependencies on sample todo app stats-api and stats-worker per dependent bot alerts.

### CODE REVIEW

**Review by Tatsinnit — APPROVED** [review]
🎉👍🙏

**Review by hsubramanianaks — APPROVED** [review]
LGTM :)

**Review by Tatsinnit — APPROVED** [review]
☕️👍 thanks for adding me for this review, looks good! (One small thing as mentioned below)

Please note: you have 2 package.lock files and only actual one package.json so I wonder if one of them is just wrong addition, you meant to add packets.json of other project as well?

Hope you have tested this with working version. Long term we should think of merging all samples into one project.

**Comment by elenavillamil** [comment]
> ☕️👍 thanks for adding me for this review, looks good! (One small thing as mentioned below)
> 
> Please note: you have 2 package.lock files and only actual one package.json so I wonder if one of them is just wrong addition, you meant to add packets.json of other project as well? Thanks heaps

Thanks for the review! I ran npm audit fix on both folder to be on the safe side, that is why the 2 lock file updates. Only one folder needed packets.json manual update to override one of the sub-dependencies.

**Pull request merged**
