### PR TITLE
WIP: .Net 7

### LINKED ISSUE #228: Upgrade to .Net 7
I have been running .Net 7 in my local builds of B2K for about 4 weeks now and everything works great.
.Net 7 have new AOT compilation features and other performance improvements that I think would be a great addition to everyone using this product.

If you want I can make a PR for upgrading it to .Net 7?

### PR DESCRIPTION
**Pull request by Eneuman**
This PR updated all projects to .Net 7

Closes #228

### CODE REVIEW

**Comment by Eneuman** [comment]
Everything seems to be working fine :)
I will switch to use this build for our development cycle for about 2 weeks to make sure no issues occures.

**Comment by hsubramanianaks** [comment]
> Everything seems to be working fine :) I will switch to use this build for our development cycle for about 2 weeks to make sure no issues occures.

@Eneuman Thanks for this PR. does your team depend on our builds or you have your own builds, test ? Please let me know.

**Comment by Eneuman** [comment]
@hsubramanianaks We have our own builds and images :)

**Review by hsubramanianaks — APPROVED** [review]
@Eneuman Thanks for this PR, really appreciate it. CI/CD pipelines changes are required before proceeding with this PR. I will work on it soon.

**Comment by hsubramanianaks** [comment]
Closing this PR since it will be taken care in PR https://github.com/Azure/Bridge-To-Kubernetes/pull/284. Thanks @Eneuman

**Pull request closed without merging**
